name: 推送ocker-Server
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'master'
  #     - 'develop'
  #     - 'Jiang-2.4.0'
  pull_request:
    types: [edited, ready_for_review, opened, synchronize, reopened]
    paths-ignore:
      - 'site/**'
      - '**/*.md'

env:
  CYPRESS_VERIFY_TIMEOUT: 180000 # https://docs.cypress.io/guides/guides/command-line#cypress-verify
  CVAT_VERSION: "local"

jobs:
  search_cache:
    if: |
      github.event.pull_request.draft == false &&
      !startsWith(github.event.pull_request.title, '[WIP]') &&
      !startsWith(github.event.pull_request.title, '[Dependent]')
    uses: ./.github/workflows/search-cache.yml

  build:
    needs: search_cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: CVAT Server从默认分支获取缓存（CVAT Server. Getting cache from the default branch）
        uses: actions/cache@v3
        with:
          path: /tmp/cvat_cache_server
          key: ${{ runner.os }}-build-server-${{ needs.search_cache.outputs.sha }}

      - name: 设置Docker Buildx（Set up Docker Buildx）
        uses: docker/setup-buildx-action@v2

      - name: 创建工件目录（Create artifact directories）
        run: |
          mkdir /tmp/cvat_server

      - name: CVAT Server构建并推送（CVAT Server. Build and push）
        uses: docker/build-push-action@v3
        with:
          cache-from: type=local,src=/tmp/cvat_cache_server
          context: .
          file: Dockerfile
          tags: cvat/server
          outputs: type=docker,dest=/tmp/cvat_server/image.tar

      # - name: 上传CVAT Server（Upload CVAT server artifact）
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: cvat_server
      #     path: /tmp/cvat_server/image.tar

      # - name: 下载CVAT Server镜像（Download CVAT server images）
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: cvat_server
      #     path: /tmp/cvat_server/

      - name: 加载Docker镜像（Load Docker images）
        run: |
          docker load --input /tmp/cvat_server/image.tar
          docker tag cvat/server:latest cvat/server:${CVAT_VERSION}
          docker image ls -a

      - name: 登录Docker Hub（Login to Docker Hub）
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 推送到Docker Hub（Push to Docker Hub）
        env:
          SERVER_IMAGE_REPO: ${{ secrets.DOCKERHUB_WORKSPACE }}/server
        run: |
          docker tag cvat/server:latest "${SERVER_IMAGE_REPO}:v2.4.0"
          docker push "${SERVER_IMAGE_REPO}:v2.4.0"

