name: 发布 Docker images
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  Push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          CLAM_AV=yes INSTALL_SOURCES=yes docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        env:
          DOCKERHUB_WORKSPACE: ${{ secrets.DOCKERHUB_WORKSPACE }}
          SERVER_IMAGE_REPO: 'server'
          UI_IMAGE_REPO: 'ui'
          TAG_NAME: 'v2.4.0'
        run: |
          docker tag "cvat/${SERVER_IMAGE_REPO}:${TAG_NAME}" "${DOCKERHUB_WORKSPACE}/${SERVER_IMAGE_REPO}:${TAG_NAME}"
          docker push "${DOCKERHUB_WORKSPACE}/${SERVER_IMAGE_REPO}:${TAG_NAME}"

        # docker push "${DOCKERHUB_WORKSPACE}/${SERVER_IMAGE_REPO}:latest"

        # docker tag "${DOCKERHUB_WORKSPACE}/${UI_IMAGE_REPO}:latest" "${DOCKERHUB_WORKSPACE}/${UI_IMAGE_REPO}:${TAG_NAME}"
        # docker push "${DOCKERHUB_WORKSPACE}/${UI_IMAGE_REPO}:${TAG_NAME}"

        # docker push "${DOCKERHUB_WORKSPACE}/${UI_IMAGE_REPO}:latest"
